FROM python:3.10-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY linear_svm_model.pkl .
COPY backend/tfidf_vectorizer.pkl .
COPY label_encoder.pkl .
COPY backend/api.py .

EXPOSE 5000

ENV MODEL_PATH=linear_svm_model.pkl
ENV VECTORIZER_PATH=tfidf_vectorizer.pkl
ENV LABEL_ENCODER_PATH=label_encoder.pkl
ENV FLASK_PORT=5000

CMD ["python", "api.py"]
