const PDFDocument = require('pdfkit');
const History = require('../models/History');

const generatePdfReport = async (req, res, analyticsData) => {
  try {
    const doc = new PDFDocument({ margin: 50 });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="spam-detection-report-${new Date().toISOString().split('T')[0]}.pdf"`);
    
    doc.pipe(res);

    // Title
    doc.fontSize(20).text('Spam & Phishing Detection Report', { align: 'center' });
    doc.moveDown();
    
    // Header Info
    doc.fontSize(12).text(`Generated On: ${new Date().toLocaleString()}`);
    if (req.user) {
      doc.text(`User ID: ${req.user.id}`);
      doc.text(`Username: ${req.user.username}`);
    }
    doc.moveDown(2);

    // Analytics Summary Section
    if (analyticsData) {
      doc.fontSize(16).text('Analytics Summary', { underline: true });
      doc.moveDown();
      
      const { total, spam, nonSpam, spamPercentage } = analyticsData;
      doc.fontSize(12).text(`Total Analyzed Messages: ${total}`);
      doc.text(`Total Spam Detected: ${spam}`);
      doc.text(`Total Safe Messages: ${nonSpam}`);
      doc.text(`Spam Percentage: ${spamPercentage ? spamPercentage.toFixed(2) : 0}%`);
      doc.moveDown(2);
    }

    // Prediction History Section
    doc.fontSize(16).text('Recent Predictions', { underline: true });
    doc.moveDown();

    // Fetch up to 20 recent predictions for the user
    const history = await History.find({ user: req.user.id })
      .sort({ createdAt: -1 })
      .limit(20);

    if (history.length === 0) {
      doc.fontSize(12).text('No predictions found.');
    } else {
      history.forEach((item, index) => {
        const typeStr = (item.type || 'UNKNOWN').toUpperCase();
        const confStr = ((item.confidence || 0) * 100).toFixed(2);
        const queryStr = item.query || '';
        const displayQuery = queryStr.length > 100 ? queryStr.substring(0, 100) + '...' : queryStr;
        
        doc.fontSize(12).font('Helvetica-Bold').text(`Prediction #${index + 1} - ${item.prediction === 'spam' ? 'SPAM/PHISHING' : 'SAFE'} (${new Date(item.createdAt).toLocaleString()})`);
        doc.font('Helvetica').text(`Type: ${typeStr}`);
        doc.text(`Confidence: ${confStr}%`);
        doc.text(`Message: "${displayQuery}"`);
        doc.moveDown();
      });
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).text('Report generated by Spam Detection System.', { align: 'center', color: 'grey' });

    doc.end();
  } catch (error) {
    console.error('PDF Generation Error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF report' });
    }
  }
};

module.exports = { generatePdfReport };
